### ISSUE TITLE
Add Custom Messages support

### ISSUE THREAD

**Issue by ivanbportugal** [getgauge-contrib/gauge-js#16]
Something like this: http://getgauge.io/documentation/user/current/test_code/csharp/custom_messages_in_reports.html
http://getgauge.io/documentation/user/current/test_code/java/custom_messages_in_reports.html

**Comment by kaustavdm** [comment]
It is on the roadmap. Should be done sometime soon.

**Comment by kaustavdm** [comment]
You can now pass custom messages using:

```js
gaugeMessage("Hello, World!");
```
Detailed example is in the [README](https://github.com/getgauge-contrib/gauge-js#custom-messages) :-)
