### ISSUE TITLE
Debugging?

### ISSUE THREAD

**Issue by ivanbportugal** [getgauge-contrib/gauge-js#18]
Is there a way to debug the step implementation? i.e. Something like the Nodejs chrome dev tools debugger?

**Comment by kaustavdm** [comment]
Yes, something like this is needed. We have not discussed this so far. So this may take some time, unless someone contributes this :-)

**Comment by kaustavdm** [comment]
@renjithgr @kashishm Any inputs on this?

**Comment by renjithgr** [comment]
I have tried [Node Inspector](https://github.com/node-inspector/node-inspector) with gauge-js. We can check the possibilities.

**Comment by ivanbportugal** [comment]
I'm not familiar with the architecture of Gauge but I'd imagine that you could bind something like `gauge debug specs` to `node-debug myStartingPoint.js` instead of `npm start` etc... How _are_ you launching the app from the gauge "hook"? I suppose that should lead you to a solution but I could be wrong :)

**Comment by kaustavdm** [comment]
We somehow need to attach the test implementation files in the debugger. My best guess is it will be in `impl_loader` around the time when the vm is fired.

**Comment by kaustavdm** [comment]
@ivanbportugal I have implemented debugging support (just now). This uses [node-inspector](https://github.com/node-inspector/node-inspector).

I have put some info in the [README section on Debugging](https://github.com/getgauge-contrib/gauge-js#debugging). I haven't tested it in Windows yet. It should work if `node-inspector` is installed. If this works under Windows, we'll do a full release soon!

@renjithgr @kashishm Help test this, please?

**Comment by kaustavdm** [comment]
I think I am hitting nodejs/node-v0.x-archive#5841 in Windows. Can anyone confirm?

**Comment by kaustavdm** [comment]
Okay, so you can now launch the debugger in Windows. But I could not get the breakpoints working on Windows. If we don't want to bother with Windows support in the first cut, we can safely say that debugging works in OSX and GNU/Linux.

Awaiting feedback...

**Comment by ivanbportugal** [comment]
Awesome, you guys rock! We use Windows on our project so I'd have to test out your solution. I'll take a look this weekend (at the latest Monday) but I wouldn't necessarily want you to have to wait for me before you release.

**Comment by kaustavdm** [comment]
I tested extensively with Windows 8 and the debugger works across `cmd` and `powershell`. :smiley_cat:

I'll close this issue now (and do a release). If anyone can reproduce debugger failure on Windows, feel free to reopen and add screenshots and stacktraces.
