### ISSUE TITLE
Expose a single global `gauge{}` object

### ISSUE THREAD

**Issue by kaustavdm** [getgauge-contrib/gauge-js#27]
Currently, all the functions are exposed globally. Let us avoid spamming the global namespace and expose a single `gauge{}` object with all the functions are methods of that object.

Also, as part of this, we should ensure that important globals like `stepRegistry`, `hookRegistry` etc. are not exposed to the test implementation code.

**Warning:** This will be a breaking change in the API. So, the documentation needs to be updated along with this.

**Comment by kaustavdm** [comment]
I am thinking of an object structure like this:

```js
global.gauge = {
  step: function (stepName, callback) {},
  hooks: {
    beforeSuite: function (callback, opts) {},
    beforeSpec: function (callback, opts) {},
    beforeScenario: function (callback, opts) {},
    beforeStep: function (callback, opts) {},
    afterStep: function (callback, opts) {},
    afterScenario: function (callback, opts) {},
    afterSpec: function (callback, opts) {},
    afterSuite: function (callback, opts) {}
  },
  message: function (msg) {},
  dataStore: {
    scenarioStore: { put: function (key, val) {}, get: function (key) {} },
    specStore: { put: function (key, val) {}, get: function (key) {} },
    suiteStore: { put: function (key, val) {}, get: function (key) {} }
  }
}
```

What say?

**Comment by renjithgr** [comment]
This looks fine to me. :+1:
