### ISSUE TITLE
Send execution time from promise resolve to Gauge core

### ISSUE THREAD

**Issue by renjithgr** [getgauge-contrib/gauge-js#3]

**Comment by kaustavdm** [comment]
This is likely an issue with the reporter plugin. I think you mean html-report here.

Nothing seems to wrong with gauge-js in this respect. I see proper timestamp in the console log, but I think the html-report rounds the timestamp wrongly.

**Comment by kaustavdm** [comment]
See the discussion at getgauge/html-report#10. You should close this issue here.

**Comment by kaustavdm** [comment]
Oh wait. The code is currently passing "0" as execution time for all steps in `src/processor/ExecuteStepProcessor.js`. That looks like the reason.

**Comment by kaustavdm** [comment]
Reopening this to use `duration` property in resolve promise in `done()` in `./src/test.js` to detect time taken for each step/hook.

**Comment by kaustavdm** [comment]
Implemented.
