### ISSUE TITLE
Separate out documentation

### ISSUE THREAD

**Issue by kaustavdm** [getgauge-contrib/gauge-js#30]
The README is getting too long, because `gauge-js` has so many features now :wink:

Should we break it down into multiple pages somewhere? If yes, where is the best place to put it?

**Comment by renjithgr** [comment]
Wiki? or multiple READMEs?

**Comment by kaustavdm** [comment]
Not sure. Gitbook? But I am not sure if I am comfortable with Gitbook :stuck_out_tongue_closed_eyes: Or could be Jekyll compiled and pushed to gh-pages by snap.

**Comment by renjithgr** [comment]
I like having documentation as a single page with subsections. But it makes sense to have it version controlled along with the source code. What do you think?

**Comment by ivanbportugal** [comment]
Actually, I think leaving it in the README is an excellent idea :)

**Comment by kaustavdm** [comment]
In that case, adding a small TOC at the top can help, maybe?

**Comment by renjithgr** [comment]
:+1:  Yeah!

**Comment by kaustavdm** [comment]
Does the current README look better? :smiley_cat:

**Comment by renjithgr** [comment]
Yes. Now it is easy to go to sections. :+1:

**Comment by kaustavdm** [comment]
Closing this!
