### ISSUE TITLE
Does autocomplete work?

### ISSUE THREAD

**Issue by philipbeadle** [getgauge-contrib/gauge-js#32]
I dont seem to get autocomplete, I started typing

* The word

in the vanilla project but nothing came up.  I expected to see the option for the implemented step :)

**Comment by kaustavdm** [comment]
Gauge-JS is a command-line utility. It does not have any IDE/text-editor integrations. We have been thinking of providing an API which text editors/IDEs can piggyback on.

We would very much welcome contributions for this!

FWIW, there is already a request on getgauge/Intellij-Plugin#119 for JS integration in IntelliJ IDEA.
