### ISSUE TITLE
No error when multiple step implementations exist

### ISSUE THREAD

**Issue by mahendrakariya** [getgauge-contrib/gauge-js#40]
Refer https://github.com/getgauge/gauge-csharp/issues/55

**Comment by ivanbportugal** [comment]
In my environment I had two steps in one Scenario. If the first one threw an error I could see it in the report. However, the second step didn't show.

Are you saying that no errors were showing up in the report at all? What did the console look like?

**Comment by mahendrakariya** [comment]
@ivanbportugal You can have multiple steps in scenarios. This issue only says that every step should have only one implementation. 

For instance, let's say there is a step `Say "Hello" to "world"`. You can use this step as many times in a spec file. But it should have only one implementation. So the following JS code should throw an error.

```javascript
gauge.step("Say <greetings> to <someone>.", function(greetings, someone) {
  // Some implementation code
});

gauge.step("Say <greetings> to <someone>.", function(greetings, someone) {
  // Some implementation code
});
```

**Comment by kaustavdm** [comment]
This is how it looks now:

<img width="809" alt="Duplicate step implementation validation error in gauge-js" src="https://cloud.githubusercontent.com/assets/364832/16421892/1f200a86-3d74-11e6-9e28-b2149263e9bc.png">
