### ISSUE TITLE
Assertion errors don't seem to show on the report

### ISSUE THREAD

**Issue by ivanbportugal** [getgauge-contrib/gauge-js#44]
Generally speaking, I am going through @philipbeadle 's approach to running webdriver.io within `gauge` steps. Some of his work is [here](https://github.com/philipbeadle/gauge-js-angular-webdriver-demo/tree/1-Using_module.exports_to_hold_Driver).

However, I am having trouble seeing assertion errors on the gauge report, even though they show up in the console. Here's what my project looks like:

`package.json`:
```javascript
devDependencies {
    "chai": "^3.5.0",
    "chai-as-promised": "^5.2.0",
    "webdriverio": "^4.0.3",
    "webdriverjs-angular": "^0.1.3"
}
```
`step_implementation.js`:
```javascript
var webdriver = require('webdriverjs-angular');

var options = {
    desiredCapabilities: {
        browserName: 'chrome'
    }
};

var chai = require('chai');
var chaiAsPromised = require('chai-as-promised');
var expect = chai.expect;
chai.Should();
var assert = require("assert");

gauge.step("Visit Google", function(done) {
    webdriver
        .remote(options)
        .init()
        .on('error', function(e) { // Sorta hacky, trying to get errors to show via emit
            gauge.message('This message never shows up');
            done('Assertion error: ' + JSON.stringify(e)); // I tried just passing 'e' here
        })
        .url('http://www.google.com/')
        .getTitle().then(function(title) {
            try {
                gauge.message('Verifying Page "' + title + '"');
                expect(title).to.equal('Google BLAH'); // Should fail, but shows up in the console, not on report.
                assert(title, 'Google BLAH'); // Doesn't even show on the console, let alone the report.
            } catch (e) { // I added this hacky try-catch to try to force gauge to fail, but I really shouldn't have to.
                gauge.message('OK... ' + JSON.stringify(e));
                this.emit('error', e);
            }
        })
        .end()
        .call(done);
});
```

So... any ideas?

**Comment by ivanbportugal** [comment]
Forgot to say one more thing... The `webdriver.io` errors DO show up. For example, if I say:

```javascript
webdriver
    .getText('#my-css-selector-that-does-not-match').then(callback)
    .end()
    .call(done);
```
That will time out and a useful error in the console will show up. However, the report will still display something bogus like `[object Object]`

**Comment by philipbeadle** [comment]
Using the webdriver inside a step is a bit pointless as you cant then move to another step with the same browser, we really need the driver instantiated externally and used in each step.

**Comment by kaustavdm** [comment]
@ivanbportugal To compare 2 values in Node's `assert`, you need to call `assert.equal(val1, val2)`. `assert()` evaluates a boolean, and it passes silently.

There seems to be some issue with the custom messages. It has stopped working for me in the Java plugin as well. Let me check if something is broken internally.

**Comment by kaustavdm** [comment]
@ivanbportugal What version of Gauge are you using? I have opened getgauge/gauge#367 in connection to this.

**Comment by kaustavdm** [comment]
This is related to #45. The issue is with the sandbox. Assertion errors crash the process.

**Comment by kaustavdm** [comment]
@philipbeadle @ivanbportugal The issues here are related to failures in asynchronous tests. You will need to use `try-catch` around the assertions or possible failures. Check [this comment](https://github.com/getgauge-contrib/gauge-js/issues/45#issuecomment-225165319) for details.
