### ISSUE TITLE
specify where step implementations are located. 

### ISSUE THREAD

**Issue by bkim54** [getgauge-contrib/gauge-js#48]
can this be possible?

**Comment by kashishm** [comment]
#41 has more details on this. @renjithgr @kaustavdm What do you think?

**Comment by bkim54** [comment]
I'm asking because I am using gauge-js with a typescript project and the typescript compiler emits .js files within the same dir as the .ts files and gauge thinks the .ts files should contain step implementations and throws the error

`Error executing tests/step.ts`

**Comment by bkim54** [comment]
any update on this?

**Comment by BugDiver** [comment]
Should be addressed through #82.
Nightly Version : 26-12-2017

**Comment by sguptatw** [comment]
Gauge [LSP Tests](https://build.getgauge.io/go/tab/pipeline/history/JS-LSP-Tests) are failing after these changes.

**Comment by sguptatw** [comment]
TestMatch by default should be w.r.t the current project directory.
