### ISSUE TITLE
Is reading test data from files available?

### ISSUE THREAD

**Issue by anupmanekar** [getgauge-contrib/gauge-js#51]
I need a way to read test data from files. Something like Special Parameter in java version.

**Comment by kashishm** [comment]
Gauge handles [Special Parameters](http://getgauge.io/documentation/user/current/gauge_terminologies/parameters/special_parameters.html#special-parameters) in a Specification file. So if you are using a special parameter in the specification, Gauge would resolve it and pass it to the step implementation in JS code.

Please follow the Node [documentation](https://nodejs.org/api/fs.html#fs_fs_readfilesync_file_options), if you want to read test data file in JavaScript code

**Comment by anupmanekar** [comment]
Thanks, I was able to achieve this.
