### ISSUE TITLE
tests directory should be renamed to specs

### ISSUE THREAD

**Issue by gbeveridge** [getgauge-contrib/gauge-js#54]
when using other gauge plugins initializing a plugin will create a **'step_impl'** or **'step_implementations'** directory where step definitions are stored. When initializing the js plugin it creates a **'tests'** directory which seems inconsistent with the plugin eco-system. I am also able to rename that directory to just **'steps'** since **'step_implementations'** is so long. It would be nice if the plugin eco-system could settle on a common name.

**Comment by BugDiver** [comment]
@gbeveridge  through the #82 the implementations dir name can be configured.

**Comment by BugDiver** [comment]
Closing the issue. fell free to reopen/comment it if you need any further discussion/suggestion.
