### ISSUE TITLE
Does gaugeJs have ES6 support?

### ISSUE THREAD

**Issue by anupmanekar** [getgauge-contrib/gauge-js#55]
I am attempting to write Jest/Enzyme tests in Gauge and I need to integrate Gauge into DEV repo. I also need to make sure that my gauge tests understands node modules written in ES6. 
So, my question is:
Is there support for ES6 constructs with Gauge? Or we need to transpile tests as well as node modules?

**Comment by sriv** [comment]
gauge-js should support ES6, provided you have the correct node runtime installed.

Feel free to log issues if you notice otherwise. Closing this question.

**Comment by alisterscott** [comment]
I can't get es6 classes to work in this PR: https://github.com/alisterscott/webdriver-js-demo/pull/13

I've posted to the google group but any ideas appreciated 🙏

**Comment by zabil** [comment]
@alisterscott es6 modules and classes are still experimental in the latest version of node according to 
https://nodejs.org/api/esm.html

Gauge does not pass `--experimental` flag while running the specs.
So this feature will only be available when es6 is enabled in a table node release.

**Comment by mwik** [comment]
What about ES6 support now? Looks like es6 modules and classes are enabled in nodejs by default now, but it does not work to import es6 modules in the step implementation file. Am I doing something wrong or is it not supported yet?
