### ISSUE TITLE
Launching an extra empty browser with my test

### ISSUE THREAD

**Issue by arjunjh10** [getgauge-contrib/gauge-js#56]
Hello Community, 
I am exploring the options of possibly implementing gauge test framework in my new project using JS and selenium-webdriver.

So far, I have been able to successfully initialize the project and add a very basic test that launches the URL in my browser and clicks on a button.

But I have run into a few issues which I am enlisting here:

1) I have modularised my driver creation in a separate file I am calling `driver.setup.js` When the tests launch it launches 2 instances of the chrome browser, one of them launches my test and the other one is a na empty browser.  How do I fix this? I have tried looking at the possibilities of why it would even happen but so far I cannot pin point at anything.

2) My Driver wont quit:
I am using the gauge hooks `afterSuite` to call `driver.quit()` but the chrome browsers just stay there and never quit even after my tests have passed and finished the execution.

My Folder Structure is :
```
src
    e2e
         env
         specs
         tests
            driver-setup.js
            steps.js
         package.json
```

The contents of my package.json are as follows:
```
{
  "name": "webdriver-tests",
  "version": "1.0.0",
  "description": "",
  "devDependencies": {
    "selenium-webdriver": "^3.4.0"
  }
}
```
Please help if possible.

**Comment by arjunjh10** [comment]
Sorry, I forgot to include how I am setting the driver :
Here are the contents of my driver-setup file
```
'use strict'

const webdriver = require('selenium-webdriver');
const chrome = require('selenium-webdriver/chrome');

const options = new chrome.Options().addArguments('--window-size=1200,800');

const driver = new webdriver.Builder()
    .forBrowser('chrome')
    .setChromeOptions(options)
    .build();

module.exports = driver;
```

I am calling it as 
```var driver = require('./driver-setup.js');```
in my steps.js


and my afterSuite hook code looks like this:
```
gauge.hooks.afterSuite(function (done) {
  driver.quit()
    .then(function () {
      done();
    });
});
```

**Comment by sriv** [comment]
There is an example that uses webdriver-io : https://github.com/philipbeadle/gauge-js-angular-webdriver-demo

Perhaps you can borrow some ideas from it?
