### ISSUE TITLE
aync test not failing

### ISSUE THREAD

**Issue by mmkumaran** [getgauge-contrib/gauge-js#57]
Hi,

I have some aync test, when the test/assertion fails it is not recognized as failure in console or in reports. any thoughts?.

Below is the sample test.
// --------------------------
// Gauge step implementations
// --------------------------

gauge.step('User can get latest plan', function(done) {
  setTimeout(function() {
    try {
      var driver = new Driver.Driver('http://localhost:80');
      driver
        .checkLatestPlan()
        .then(res => {
          done();
           assert.equal(true, false);
        })
        .catch(err => {
          console.error(err);
        });
    } catch (e) {
      done(e);
    }
  }, 5000);
});

console output
============
# Specification Heading
  ## Plan    Socket Connection Initiated
Socket connection Established
{ AssertionError: true == false
    at driver.checkLatestPlan.then.res (tests\acceptance-test.js:20:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
  name: 'AssertionError',
  actual: true,
  expected: false,
  operator: '==',
  message: 'true == false',
  generatedMessage: true }
 P

Successfully generated html-report to => D:\workspace\bumblebee\bumblebee-integration-tests\gauge\reports\html-report
Specifications: 1 executed      1 passed        0 failed        0 skipped
Scenarios:      1 executed      1 passed        0 failed        0 skipped

Versions: 
Gauge version: 0.8.4
Plugins
-------
html-report (4.0.0)
js (2.0.0)

**Comment by sriv** [comment]
You seem to be passing the assertion error to the console and that isn't getting bubbled to Gauge.

Something like this should throw the assertion error:

Spec
---

```
Sample
=====

Vowel Definition
----------------

* Vowels in English language are "aeiou".
```

Implementation
---

```
var assert = require("assert");

var vowels = ["a", "e", "i", "o", "u"];

var vowelPromise = function(){
  return new Promise((resolve, reject) =>{
    if(vowels)
      resolve(vowels);
    else
      reject();
  })
}

gauge.step("Vowels in English language are <vowels>.", function(vowelsGiven, done) {
  return vowelPromise().then(
    (v) =>  assert.equal("not vowels", v.join(""))
  ).catch((e) => done(e));
});
```

**Comment by mmkumaran** [comment]
hi Sriv,

thanks for your suggestion, adding done(e) to the promise catch and re-ording assert and done() has solved the issue. below is the working code..

below is the working example code.
gauge.step('User can get latest plan - failing', function(done) {
  setTimeout(function() {
    try {
      var driver = new Driver.Driver('http://localhost');
      driver
        .checkLatestPlan()
        .then(res => {
           assert.equal(true, false);
          done();
        })
        .catch(err => {
          done(err);
          });
    } catch (e) {
      done(e);
    }
  }, 1000);
});

Thanks,
Muthu
