### ISSUE TITLE
Refactoring is broken

### ISSUE THREAD

**Issue by sguptatw** [getgauge-contrib/gauge-js#69]
**Expected behavior**
User should be able to refactor a step

**Actual behavior**
Refactoring one step is changing all other step annotations in the file

**Steps to replicate**
* create a new js project
* gauge refactor 'The word "gauge" has "3" vowels.' 'ord "gauge" has "3" vowels.'
* open step_implementation.js
> all step annotation texts have been changed.

**Version**
```
Gauge version: 0.9.5

Plugins
-------
csharp (0.10.2.nightly-2017-10-26)
html-report (4.0.2)
java (0.6.6.nightly-2017-09-14)
js (2.0.3.nightly-2017-11-09)
ruby (0.4.3.nightly-2017-10-17)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)
```

**Comment by BugDiver** [comment]
Fix should be available in nightly > 10-11-2017
