### ISSUE TITLE
Make test timeout configurable.

### ISSUE THREAD

**Issue by renjithgr** [getgauge-contrib/gauge-js#7]
Right now every test has a timeout of 1000ms. Ideally it should be configurable.

**Comment by kaustavdm** [comment]
I see that this is already configurable in `./src/test.js`. Do you mean we should let the global `gauge()` method to take an optional parameter for the test timeout for each step?

**Comment by renjithgr** [comment]
Yeah it is configurable in ```./src/test.js```. But right now we are not passing anything to it and it will use the default 1000ms. It should be configurable for each project through a property file. I think other runners also have some ability to specify properties in external file, right?

**Comment by renjithgr** [comment]
Picking this up.

**Comment by kaustavdm** [comment]
@renjithgr There will be some breaking changes in the next 2 days in step registry and executor to implement refactoring. Make sure you keep merging `master` to avoid conflicts.

**Comment by renjithgr** [comment]
Yeah, sure.
