### ISSUE TITLE
The line number of failure is one more than the line of error

### ISSUE THREAD

**Issue by sguptatw** [getgauge-contrib/gauge-js#73]
**Expected behavior**
When there is an error, the line number of failure should be the line where the error occurred

**Actual behavior**
It is one more than the line where the error occured

**Steps to replicate**
* Create a gauge js project
* Have a step fail
* run the specs
* Observe the line number of the code failure

**Version**
```
Gauge version: 0.9.5.nightly-2017-11-15
Commit Hash: 55fe281

Plugins
-------
js (2.0.3.nightly-2017-11-15)
```

**Comment by sriv** [comment]
fix available in nightly > 23/11/2017
