### ISSUE TITLE
Test Scenario Context is missing

### ISSUE THREAD

**Issue by OrangeBean** [getgauge-contrib/gauge-js#80]
Hi guys,

I was reading the code and believe this functionality is missing. The objective is: 
Test scenario consists of multiple steps and outcome of one step can be reused in another step. Then I could implement heavy/shared assertion logic in separate step and reuse it in multiple test scenarios.

 It would greatly enhance readability of the test scenario if the test scenario context would be introduced. 

It would make following test scenarios possible:
```
Retrieved individual customer profile contains phone
----------------------------------------------------
* Customer details retrieved for customer "Lynda Buggy"
* profile belong to "individual"
* profile contains phone "12345678"

Retrieved company profile contains phone
----------------------------------------
* Customer details retrieved for customer "Conteco Pty"
* profile belong to "company"
* profile contains phone "23456789"
```

**Comment by BugDiver** [comment]
@OrangeBean There is a similar [proposed feature](https://github.com/getgauge/gauge/issues/531) in `gauge`. You can upvote, add your use case/findings and follow that for more updates.

**Comment by OrangeBean** [comment]
It's not quite the same.

**Comment by OrangeBean** [comment]
My bad. I didn't read doco in full. There are [Data Stores](https://getgauge-contrib.github.io/gauge-js/syntax/data-stores.html). This is what I was looking for.
