### ISSUE TITLE
Stacktrace with error in js line should be clickable

### ISSUE THREAD

**Issue by sguptatw** [getgauge-contrib/gauge-js#83]
**Expected behavior**
The line number indicating the error in js file should be clickable.

**Actual behavior**
When the error is request timeout the stacktrace indicating the failure is not clickable

**Steps to replicate**
* LSP Tests with request timeout 
> Observe the `goto definition spec error` in the stacktrace https://travis-ci.org/getgauge/gauge-lsp-tests/builds/315198558

**Version**
```
Gauge version: 0.9.6.nightly-2017-12-08
Commit Hash: 0b85c7e
Plugins
-------
html-report (4.0.3.nightly-2017-12-08)
js (2.0.3.nightly-2017-11-30)
xml-report (0.2.1.nightly-2017-10-26)
```

**Comment by sguptatw** [comment]
**Issue**
The error path is getting concatenated with relative path twice

**Steps to replicate**
* Project - [WrongPathInJS.zip](https://github.com/getgauge-contrib/gauge-js/files/1557923/WrongPathInJS.zip)
* Run spec `concept diagnostics.spec`
> Observe the error stack having multiple relative paths
```
TypeError: vscodeUri.file is not a function
            at Object.getFullPath (...\getgauge\gauge-lsp-tests\...\getgauge\gauge-lsp-tests\tests\util\fileExtension.js:8:22)
            at Object.startGaugeDaemon (...\getgauge\gauge-lsp-tests\tests\lsp\daemon.js:14:30)
            at Object.<anonymous> (tests\gaugeDaemon.js:4:18)
```

**Comment by sguptatw** [comment]
**Issue**
Current project path is getting appended to external library

**Steps to replicate**
var path = require('path')

var relativePath = someValidPath
var filePath= null
path.join(relativePath, filePath)

When there is a failure in path library, the stacktrace indicates current projectdir/path.js. This is the wrong information.

**Comment by Apoorva-GA** [comment]
@sguptatw the above issue looks like a different issue. Could you please create a new issue?

**Comment by riju91** [comment]
Vscode's default document link provider does not support spaces in filenames. Incorrect Document links are generated for the files which have space in their names since only the part of the filename till the first space in considered for the link which result in incorrect links.
Possible resolution could be adding custom document link providers.

**Comment by sguptatw** [comment]
Tracking other issues in different issue cards.
