### ISSUE TITLE
The annotation text of the generated code should have valid parameter details

### ISSUE THREAD

**Issue by sguptatw** [getgauge-contrib/gauge-js#85]
**Actual behavior**
* The step text of step implementation generated has parameter value instead of the name

**Steps to replicate**
* Add step 
```
step with parameter </specs/afterFormat.spec>
```
* generate stub details
>Observe the generated code has step text
```
step with parameter </specs/afterFormat.spec>
```
This can be `step with parameter <arg0>`

**Version**
```
Gauge version: 0.9.6.nightly-2017-12-13
Commit Hash: 571fda8

Plugins
-------
js (2.0.3.nightly-2017-12-15)
```

**Comment by BugDiver** [comment]
FIx should be available in nightly >= 26-12-2017
