### ISSUE TITLE
Continues on failure even if not configured for it

### ISSUE THREAD

**Issue by sguptatw** [getgauge-contrib/gauge-js#86]
**Expected behavior**
Should continue on failure only if it is configured to do so.

**Actual behavior**
Even if a step has failed, the next step is getting executed.

**Steps to replicate**
* https://travis-ci.org/getgauge/gauge-lsp-tests/builds/318069883
> Observe all the scenarios which have failed here. It has failing step and has continued the execution

**Version**
```
Gauge version: 0.9.6.nightly-2017-12-13
Commit Hash: 571fda8

Plugins
-------
js (2.0.3.nightly-2017-12-15)
```

**Comment by BugDiver** [comment]
@sguptatw looks like the last passing steps are `teardown`. `gauge` executes `teardown` even the execution of steps fails.

**Comment by BugDiver** [comment]
@sguptatw Not able to replicate with latest `gauge` and `gauge-js`
