### ISSUE TITLE
The error path in the stack trace is incomplete

### ISSUE THREAD

**Issue by sguptatw** [getgauge-contrib/gauge-js#87]
_From @sguptatw on December 18, 2017 6:54_

**Expected behavior**
The error path in the stack trace should be complete

**Actual behavior**
The error path is incomplete

**Steps to replicate**
* Run project [errors_with_incomplete_Path.zip](https://github.com/getgauge/gauge-vscode/files/1566895/errors_with_incomplete_Path.zip)
> Observe the path in the error
```
AssertionError [ERR_ASSERTION]: 0 not equal to 1
            at verifyAutocompleteResponse (tests\codecomplete.js:59:12)
            at Object.<anonymous> (tests\codecomplete.js:29:5)
```
**Version**
```
Gauge version: 0.9.6.nightly-2017-12-13
Commit Hash: 571fda8

Plugins
-------
js (2.0.3.nightly-2017-12-15)
```

_Copied from original issue: getgauge/gauge-vscode#80_

**Comment by riju91** [comment]
Feature available in getgauge/gauge-vscode
