### ISSUE TITLE
The error path is getting concatenated with relative path twice

### ISSUE THREAD

**Issue by sguptatw** [getgauge-contrib/gauge-js#88]
_From @sguptatw on December 18, 2017 6:38_

**Expected behavior**
The error path in the stacktrace should be correct

**Actual behavior**
The error path is getting concatenated with relative path twice

**Steps to replicate**
* Project - [WrongPathInJS.zip](https://github.com/getgauge-contrib/gauge-js/files/1557923/WrongPathInJS.zip)
* npm install
* Run spec `concept diagnostics.spec`
> Observe the error stack having multiple relative paths
```
TypeError: vscodeUri.file is not a function
            at Object.getFullPath (...\getgauge\gauge-lsp-tests\...\getgauge\gauge-lsp-tests\tests\util\fileExtension.js:8:22)
            at Object.startGaugeDaemon (...\getgauge\gauge-lsp-tests\tests\lsp\daemon.js:14:30)
            at Object.<anonymous> (tests\gaugeDaemon.js:4:18)
```

**Version**
```
Gauge version: 0.9.6.nightly-2017-12-13
Commit Hash: 571fda8

Plugins
-------
js (2.0.3.nightly-2017-12-15)
```

_Copied from original issue: getgauge/gauge-vscode#79_

**Comment by BugDiver** [comment]
Not able to replicate with latest `gauge` and `js`.

**Comment by sguptatw** [comment]
Able to replicate it with gauge version
```
Gauge version: 0.9.7.nightly-2017-12-27
Commit Hash: 9f8dd0f

Plugins
-------
js (2.1.0.nightly-2017-12-26)
```
> Note: run `npm install` in the project folder before running the tests

**Comment by Apoorva-GA** [comment]
Not replicable with latest 'gauge' and 'gauge-js'.

**Comment by sguptatw** [comment]
This is replicable when you run from VSCode. Will open an issue there.
