### ISSUE TITLE
Execution of specs gives Error - Unable to require module

### ISSUE THREAD

**Issue by sguptatw** [getgauge-contrib/gauge-js#94]
**Expected behavior**
Should be able to execute specs without errors

**Actual behavior**
Getting the error
```
Unable to require module 
```

**Steps to replicate**
* run [LSP Tests](https://github.com/getgauge/gauge-lsp-tests) from VSCode
> Note: OS - Winodws 10
npm version
{ 'gauge-lsp-tests': '0.0.1',
  npm: '5.6.0',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.9.4',
  openssl: '1.0.2n',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.15.0',
  v8: '6.1.534.50',
  zlib: '1.2.11' }

**Version**
```
Gauge version: 0.9.7.nightly-2018-01-04
Commit Hash: aa963f8

Plugins
-------
js (2.1.0.nightly-2018-01-03)
```

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge-js nightly >= 11/01/18
